#! /bin/sh

restart() {
    pkill "$1"; $1 >/dev/null &
}

nvidia-settings --load-config-only
numlockx
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
restart nm-applet
restart blueman-applet
restart dunst
restart birdtray
pkill kdeconnect-indi; kdeconnect-indicator >/dev/null &
pkill greenclip; greenclip daemon >/dev/null &

~/.local/bin/mount_karl.sh
ssh -D 9090 -fN ywa

restart sxhkd

# hsetroot -solid "#2E2641"
~/.fehbg

killall -q polybar
polybar bar0 &
polybar bar1 &

xsetroot -cursor_name left_ptr

# restart picom

# Monitors
bspc monitor DP-0 -d 11 12 13 14 15
bspc monitor DP-2 -d 21 22 23 24 25

# Mouse configs
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Settings
bspc config normal_border_color     "#44475a"
bspc config active_border_color     "#bd93f9"
bspc config focused_border_color    "#ae41aa"
bspc config presel_feedback_color   "#6272a4"

bspc config top_padding         36
bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true

bspc config single_monocle true
bspc config automatic_scheme alternate
bspc config ignore_ewmh_focus true
bspc config directional_focus_tightness low
# bspc config swallow_first_click true
