#!/bin/sh

count() {
    pcount=`pactl list source-outputs short | wc -l`
    if [[ $pcount -ne "0" ]]; then
        echo $pcount
    else
        echo ""
    fi
}

count
pactl subscribe | while read -r event; do
    if echo "$event" | grep -q "source" || echo "$event" | grep -q "server"; then
        count
    fi
done
