"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [0, 4, 3]
sort_by = "natural"
sort_sensitive = false
linemode = "size_and_mtime"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "Yazi: {cwd}"

# [opener]
# lowriter = [{ run = 'lowriter "$@"', block = true }]
#
# [open]
# rules = [{ name = "*.docx", use = "lowriter" }]
