#! /bin/sh

pkill sxhkd
sxhkd -c ~/.config/sxhkd/sxhkdrc.d/* ~/.config/sxhkd/wm/bspwm &

~/.config/polybar/start.sh &
~/.local/bin/startup.sh &

# Monitors
# bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-0 -d 11 12 13 14 15
bspc monitor DP-2 -d 21 22 23 24 25

# Mouse configs
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config click_to_focus any

# Settings
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ae41aa"
bspc config presel_feedback_color "#6272a4"

bspc config top_padding 36
bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true

bspc config single_monocle true
bspc config automatic_scheme longest_side
bspc config ignore_ewmh_focus true
bspc config directional_focus_tightness low
# bspc config swallow_first_click true

# bspc config pointer_motion_interval 8

bspc rule -a pavucontrol state=floating
bspc rule -a copyq state=floating
bspc rule -a TelegramDesktop state=floating desktop=21
