#!/bin/env bash

nodes=($(bspc query -N -n .hidden))
titles=${nodes[@]}
[[ ${#nodes[@]} != 0 ]] && titles=$(xtitle ${titles[@]})
sel=$(printf "%s\n" "${titles[@]}" | rofi -dmenu -i -format i -p "Hidden windows")

if [[ -n "$sel" ]]; then
	dest=n
	bspc query -N -n >/dev/null || dest=d
	bspc node "${nodes[$sel]}" -${dest} focused -g hidden=off -f
fi
